//! AOT compiler for AINL: AST (`ainl_core::Node`) -> a single self-contained
//! C file -> `cc`. Zero external dependencies (reuses ainl-core's AST).
//!
//! This is a scaffold — the full codegen + micro-runtime land in follow-up
//! commits (checkpoint-commit discipline per the PO).

use ainl_core::Node;

/// Generate a self-contained C source file for the given top-level forms.
pub fn generate(_forms: &[Node]) -> String {
    String::from(
        "/* Generated by ainl compile (scaffold) */\n#include <stdio.h>\nint main(void){\n  printf(\"hello, AOT!\\n\");\n  return 0;\n}\n",
    )
}
